### PR TITLE
[BACK-2984] Resolve dependabot issues

### PR DESCRIPTION
**Pull request by darinkrauss**
- Fix dependencies issues and vulnerabilities
- Use modern version of yarn
- Update .travis.yml
- Update .gitgnore
- Add .yarnrc.yml
- Add .nvmrc
- Add .snyk
- https://tidepool.atlassian.net/browse/BACK-2984

### CODE REVIEW

**Review by jh-bate — DISMISSED** [review]
LGTM

NOTE `"version": "2.4.2-alpha.1",` so just wanted to check that was intended

**Comment by darinkrauss** [comment]
Thanks, yes, that's intentional. Once it is tested I'll move it to 2.4.2, release a new version, and pick up that change in the export repo.

**Review by jh-bate — DISMISSED** [review]
LGTM - I am assuming this is still meant to be an alpha tag

**Review by jh-bate — APPROVED** [review]
LGTM - version no longer alpha :)

**Pull request merged**
